### ISSUE TITLE
Workflow example

### ISSUE THREAD

**Issue by kbrock** [chrisarcand/miqversions#11]
Can you provide a shell script or edit the readme to show how you release a new version and pour a new "bottle"?

Thnx

**Comment by chrisarcand** [comment]
Sure can, though note this is low priority for me (as you might tell) with the holiday wrap up. I'll get to you!

I have to rediscover how I do it almost every release, is the issue. I thought I had it written down somewhere though.

Note that the native install is a tiny convenience more than anything else, just have Go installed and it'll take a few extra seconds just to compile the latest from source (using the same cask/install steps).

**Comment by kbrock** [comment]
Thanks Chris,
And yea, very low priority

**Comment by chrisarcand** [comment]
@kbrock Thanks for your patience! Here's my notes on how I release this project on Homebrew. I wrote these down because I basically had to completely re-learn everything again each time. They might not be the most correct mind you, but it's what I pieced together for my uses.

* Push a new tag to GitHub. The tar.gz is automatically created (`https://github.com/chrisarcand/miqversions/archive/vx.x.x.tar.gz`)
* `brew edit <formula>`; Edit the tarball URL (above) to the new version
* `brew upgrade --build-from-source --build-bottle ~<formulae>~`
* You'll get a SHA256 mismatch, because you didn't update the SHA from the file in Step 1 because lazy. That's ok; just copy the new one into the formula. ^_^
* Run the update command again
* Now run `brew bottle <formula>` which will create the bottle in the current dir (the "bottle") and give you the bottle block to add to the formula. Make sure update the `root_url` too.
* Lastly, manually add the 'bottle' to the release in the GitHub UI

Hope that helps!  Cheers
